services:
  server:
    build:
      context: ./FlightsApp/Backend/Flights
      dockerfile: Dockerfile
    restart: always
    container_name: "flights-server"
    hostname: "flights-server"   
    ports:
      - 5000:80  
    environment:
      - PORT=5000
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy


  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: XWS_Projekat
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

volumes:
  mongo_store:
