# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  flights:
    image: flights
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5010:5010
  
  flights_db:
    image: mongo
    restart: always
    ports:
      - "27030:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: XWS_Projekat
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - flights_store:/data/db
  
volumes:
  flights_store:


