global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:80']

  - job_name: 'accommodation-service'
    static_configs:
      - targets: ['accommodation-service:80']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']

  - job_name: 'flight-recommendation-service'
    static_configs:
      - targets: ['flight-recommendation-service:80']

  - job_name: 'reservation-service'
    static_configs:
      - targets: ['reservation-service:80']

  - job_name: 'rating-service'
    static_configs:
      - targets: ['rating-service:80']

  - job_name: node
    static_configs:
      - targets: ['windows-exporter:9100']

  
